-- lms_courses table
CREATE TABLE IF NOT EXISTS public.lms_courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    content TEXT,
    type TEXT NOT NULL DEFAULT 'Course',
    class_level TEXT,
    language TEXT,
    price DECIMAL(10,2) DEFAULT 0,
    curriculum JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.lms_courses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Courses viewable by everyone" ON public.lms_courses FOR SELECT USING (true);
CREATE POLICY "Admins can insert courses" ON public.lms_courses FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('Admin', 'Super Admin'))
);
CREATE POLICY "Admins can update courses" ON public.lms_courses FOR UPDATE USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('Admin', 'Super Admin'))
);

-- course_progress table
CREATE TABLE IF NOT EXISTS public.course_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    course_id BIGINT REFERENCES public.lms_courses(id) ON DELETE CASCADE,
    completed_topics JSONB DEFAULT '[]'::jsonb,
    status TEXT DEFAULT 'IN_PROGRESS',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    UNIQUE(user_id, course_id)
);

ALTER TABLE public.course_progress ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own course progress" ON public.course_progress FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own course progress" ON public.course_progress FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own course progress" ON public.course_progress FOR UPDATE USING (auth.uid() = user_id);

-- certificate_requests table
CREATE TABLE IF NOT EXISTS public.certificate_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    course_id BIGINT REFERENCES public.lms_courses(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    certificate_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    UNIQUE(user_id, course_id)
);

ALTER TABLE public.certificate_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own certificate requests" ON public.certificate_requests FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own certificate requests" ON public.certificate_requests FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Admins can view all certificate requests" ON public.certificate_requests FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('Admin', 'Super Admin'))
);
CREATE POLICY "Admins can update all certificate requests" ON public.certificate_requests FOR UPDATE USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('Admin', 'Super Admin'))
);

-- unified_master_data table (used by AstroEdge etc)
CREATE TABLE IF NOT EXISTS public.unified_master_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL,
    data JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.unified_master_data ENABLE ROW LEVEL SECURITY;
CREATE POLICY "unified master data viewable by everyone" ON public.unified_master_data FOR SELECT USING (true);
CREATE POLICY "Admins can update unified master data" ON public.unified_master_data FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('Admin', 'Super Admin'))
);

-- moneyo_savings table
CREATE TABLE IF NOT EXISTS public.moneyo_savings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    scheme_name TEXT NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    status TEXT DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.moneyo_savings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own moneyo savings" ON public.moneyo_savings FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own moneyo savings" ON public.moneyo_savings FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Admins can view all moneyo savings" ON public.moneyo_savings FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('Admin', 'Super Admin'))
);

-- touro table
CREATE TABLE IF NOT EXISTS public.touro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    tour_name TEXT NOT NULL,
    booking_details JSONB,
    status TEXT DEFAULT 'PENDING',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.touro ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own touro" ON public.touro FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own touro" ON public.touro FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Admins can view all touro" ON public.touro FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('Admin', 'Super Admin'))
);
-- Run this in your Supabase SQL Editor to create or update the database schema

-- 1. Users Table (Extends Supabase Auth)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT NOT NULL,
  role TEXT DEFAULT 'User' CHECK (role IN ('User', 'Seller', 'Instructor', 'Local Admin', 'Admin', 'Super Admin')),
  whatsapp TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Secure Profiles Table with RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public profiles are viewable by everyone" ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

DROP POLICY IF EXISTS "Admins can update all profiles" ON public.profiles;
CREATE POLICY "Admins can update all profiles" ON public.profiles FOR UPDATE USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('Admin', 'Super Admin'))
);

-- 2. Marketplace Products Table
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seller_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL(10,2) NOT NULL,
  category TEXT NOT NULL,
  status TEXT DEFAULT 'PENDING_ADMIN' CHECK (status IN ('PENDING_ADMIN', 'PUBLISHED', 'REJECTED')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Secure Products with RLS
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Published products are viewable by everyone" ON public.products;
CREATE POLICY "Published products are viewable by everyone" ON public.products FOR SELECT USING (status = 'PUBLISHED' OR auth.uid() = seller_id);

DROP POLICY IF EXISTS "Sellers can insert products" ON public.products;
CREATE POLICY "Sellers can insert products" ON public.products FOR INSERT WITH CHECK (auth.uid() = seller_id);

DROP POLICY IF EXISTS "Admins can update products" ON public.products;
CREATE POLICY "Admins can update products" ON public.products FOR UPDATE USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('Admin', 'Super Admin'))
);

-- 3. Finance Loans Table
CREATE TABLE IF NOT EXISTS public.loans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  applicant_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  business_name TEXT NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  purpose TEXT,
  funded_percentage INTEGER DEFAULT 0,
  status TEXT DEFAULT 'SUBMITTED' CHECK (status IN ('SUBMITTED', 'APPROVED', 'FUNDED', 'REJECTED')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Secure Loans with RLS
ALTER TABLE public.loans ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Approved loans viewable by all" ON public.loans;
CREATE POLICY "Approved loans viewable by all" ON public.loans FOR SELECT USING (status = 'APPROVED' OR auth.uid() = applicant_id);

DROP POLICY IF EXISTS "Users can apply for loans" ON public.loans;
CREATE POLICY "Users can apply for loans" ON public.loans FOR INSERT WITH CHECK (auth.uid() = applicant_id);

DROP POLICY IF EXISTS "Admins can update loans" ON public.loans;
CREATE POLICY "Admins can update loans" ON public.loans FOR UPDATE USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('Admin', 'Super Admin'))
);

-- 4. Universal Ecosystem Listings
CREATE TABLE IF NOT EXISTS public.listings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lister_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  price DECIMAL(12,2),
  type TEXT NOT NULL CHECK (type IN ('Product', 'Land', 'Course', 'Grocery', 'Farmer')),
  details JSONB,
  status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.listings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Listings viewable by everyone if approved or own" ON public.listings;
CREATE POLICY "Listings viewable by everyone if approved or own" ON public.listings FOR SELECT USING (status = 'APPROVED' OR auth.uid() = lister_id OR EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('Admin', 'Super Admin')));

DROP POLICY IF EXISTS "Users can insert listings" ON public.listings;
CREATE POLICY "Users can insert listings" ON public.listings FOR INSERT WITH CHECK (auth.uid() = lister_id);

DROP POLICY IF EXISTS "Users can update own PENDING listings" ON public.listings;
CREATE POLICY "Users can update own PENDING listings" ON public.listings FOR UPDATE USING (auth.uid() = lister_id AND status = 'PENDING');

DROP POLICY IF EXISTS "Admins can update all listings" ON public.listings;
CREATE POLICY "Admins can update all listings" ON public.listings FOR UPDATE USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('Admin', 'Super Admin')));

-- 5. Real-Time Chat / Messages Table
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listing_id BIGINT REFERENCES public.listings(id) ON DELETE CASCADE,
  sender_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Messages viewable by admin or lister" ON public.messages;
CREATE POLICY "Messages viewable by admin or lister" ON public.messages FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.listings WHERE id = listing_id AND lister_id = auth.uid()) OR
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('Admin', 'Super Admin'))
);

DROP POLICY IF EXISTS "Users and Admins can insert messages" ON public.messages;
CREATE POLICY "Users and Admins can insert messages" ON public.messages FOR INSERT WITH CHECK (
  auth.uid() = sender_id AND (
    EXISTS (SELECT 1 FROM public.listings WHERE id = listing_id AND lister_id = auth.uid()) OR
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('Admin', 'Super Admin'))
  )
);

-- Enable Realtime
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime;
commit;
alter publication supabase_realtime add table messages;
alter publication supabase_realtime add table listings;
-- Create the notifications table
CREATE TABLE IF NOT EXISTS public.notifications (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Allow system/admins to insert notifications
CREATE POLICY "Admins can insert notifications" 
ON public.notifications FOR INSERT 
WITH CHECK (true);

-- Allow users to read their own notifications
CREATE POLICY "Users can view their own notifications" 
ON public.notifications FOR SELECT 
USING (auth.uid() = user_id);

-- Allow users to update their own notifications (e.g. mark as read)
CREATE POLICY "Users can update their own notifications" 
ON public.notifications FOR UPDATE
USING (auth.uid() = user_id);
-- Create the purchases table
CREATE TABLE IF NOT EXISTS public.purchases (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    item_id TEXT NOT NULL,
    item_type TEXT NOT NULL,
    payment_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.purchases ENABLE ROW LEVEL SECURITY;

-- Allow users to insert their own purchases
CREATE POLICY "Users can insert their own purchases" 
ON public.purchases FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- Allow users to read their own purchases
CREATE POLICY "Users can view their own purchases" 
ON public.purchases FOR SELECT 
USING (auth.uid() = user_id);

-- Allow admins to read all purchases
-- Note: Assuming you have a way to check admins in your policies, otherwise allow authenticated users to read all for now, or just trust the app logic.
CREATE POLICY "Admins can view all purchases" 
ON public.purchases FOR SELECT 
USING (true); -- You can restrict this if you have an admin role check

-- Allow admins to update purchases
CREATE POLICY "Admins can update purchases" 
ON public.purchases FOR UPDATE
USING (true);
