-- ============================================================
-- TradeO Schema
-- ============================================================

CREATE TABLE IF NOT EXISTS public.tradeo_listings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    price DECIMAL(10,2) NOT NULL,
    status TEXT DEFAULT 'AVAILABLE',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.tradeo_listings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view available listings" ON public.tradeo_listings FOR SELECT USING (status = 'AVAILABLE' OR auth.uid() = seller_id);
CREATE POLICY "Users can insert own listings" ON public.tradeo_listings FOR INSERT WITH CHECK (auth.uid() = seller_id);
CREATE POLICY "Users can update own listings" ON public.tradeo_listings FOR UPDATE USING (auth.uid() = seller_id);
CREATE POLICY "Users can delete own listings" ON public.tradeo_listings FOR DELETE USING (auth.uid() = seller_id);
