-- ============================================================
-- TvO Schema
-- ============================================================

CREATE TABLE IF NOT EXISTS public.tvo_videos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    video_url TEXT NOT NULL,
    thumbnail_url TEXT,
    views_count INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.tvo_videos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can view videos" ON public.tvo_videos FOR SELECT USING (true);
CREATE POLICY "Creators can insert own videos" ON public.tvo_videos FOR INSERT WITH CHECK (auth.uid() = creator_id);
CREATE POLICY "Creators can update own videos" ON public.tvo_videos FOR UPDATE USING (auth.uid() = creator_id);
CREATE POLICY "Creators can delete own videos" ON public.tvo_videos FOR DELETE USING (auth.uid() = creator_id);
