-- lms_courses table
CREATE TABLE IF NOT EXISTS public.lms_courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    content TEXT,
    type TEXT NOT NULL DEFAULT 'Course',
    class_level TEXT,
    language TEXT,
    price DECIMAL(10,2) DEFAULT 0,
    curriculum JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.lms_courses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Courses viewable by everyone" ON public.lms_courses FOR SELECT USING (true);
CREATE POLICY "Admins can insert courses" ON public.lms_courses FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('Admin', 'Super Admin'))
);
CREATE POLICY "Admins can update courses" ON public.lms_courses FOR UPDATE USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('Admin', 'Super Admin'))
);

-- course_progress table
CREATE TABLE IF NOT EXISTS public.course_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    course_id BIGINT REFERENCES public.lms_courses(id) ON DELETE CASCADE,
    completed_topics JSONB DEFAULT '[]'::jsonb,
    status TEXT DEFAULT 'IN_PROGRESS',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    UNIQUE(user_id, course_id)
);

ALTER TABLE public.course_progress ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own course progress" ON public.course_progress FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own course progress" ON public.course_progress FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own course progress" ON public.course_progress FOR UPDATE USING (auth.uid() = user_id);

-- certificate_requests table
CREATE TABLE IF NOT EXISTS public.certificate_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    course_id BIGINT REFERENCES public.lms_courses(id) ON DELETE CASCADE,
    status TEXT DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    certificate_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    UNIQUE(user_id, course_id)
);

ALTER TABLE public.certificate_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own certificate requests" ON public.certificate_requests FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own certificate requests" ON public.certificate_requests FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Admins can view all certificate requests" ON public.certificate_requests FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('Admin', 'Super Admin'))
);
CREATE POLICY "Admins can update all certificate requests" ON public.certificate_requests FOR UPDATE USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('Admin', 'Super Admin'))
);

-- unified_master_data table (used by AstroEdge etc)
CREATE TABLE IF NOT EXISTS public.unified_master_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL,
    data JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.unified_master_data ENABLE ROW LEVEL SECURITY;
CREATE POLICY "unified master data viewable by everyone" ON public.unified_master_data FOR SELECT USING (true);
CREATE POLICY "Admins can update unified master data" ON public.unified_master_data FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('Admin', 'Super Admin'))
);

-- moneyo_savings table
CREATE TABLE IF NOT EXISTS public.moneyo_savings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    scheme_name TEXT NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    status TEXT DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.moneyo_savings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own moneyo savings" ON public.moneyo_savings FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own moneyo savings" ON public.moneyo_savings FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Admins can view all moneyo savings" ON public.moneyo_savings FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('Admin', 'Super Admin'))
);

-- touro table
CREATE TABLE IF NOT EXISTS public.touro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    tour_name TEXT NOT NULL,
    booking_details JSONB,
    status TEXT DEFAULT 'PENDING',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.touro ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own touro" ON public.touro FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own touro" ON public.touro FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Admins can view all touro" ON public.touro FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('Admin', 'Super Admin'))
);
